# Generated by Django 5.0.6 on 2024-12-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_newuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
    ]
